### ISSUE TITLE
date time support

### ISSUE THREAD

**Issue by j209** [javadbat/jb-date-input#16]
Hi
Does this library support time?i want to have date and time in a datetime picker

**Comment by javadbat** [comment]
hello
this library doesn't support Time but you can use jb-time-input to get time from the user.
https://github.com/javadbat/jb-time-input
if you need any help or feature fell free to ask.

**Comment by j209** [comment]
thanks
how i can Combine the date and time inputs in one field? like [this](https://majidh1.github.io/JalaliDatePicker/) library?

**Comment by javadbat** [comment]
you may use css variables to hide borders and background of component and create your own box that contain both of them.
