### ISSUE TITLE
Feature Request: Customize Month Names for Afghan Calendar

### ISSUE THREAD

**Issue by SabawoonDaqiq8** [javadbat/jb-date-input#17]
I need to customize the month names to reflect the Afghan calendar instead of the default Iranian names. Could you consider adding a feature in jb-date-input for users to set custom month names?

**Comment by javadbat** [comment]
sure

**Comment by javadbat** [comment]
https://github.com/javadbat/jb-date-input/commit/12c6435b2c24735fe51b23c486aeea299ced46bb
